# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca798659a157540b48e22df2ca9fea770ca0dcffc6f122c345021d7f5a7ad3ad847edb3709c75251a9da95b4d7950c7afbf7fff7007746fd3cd56d57c81c5ae6

test:
  secret_key_base: c1cb56191b1d977a08803012a0f6038772abaf8584184d53e1f269006152883912f42587e04271d652021bf65e9d6bfc79ae2b22c5fee400953defdbaa2b21dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
